parameter_defaults: 
  ManilaCephFSNativeBackendName: cephfsnative
  ManilaCephFSNativeDriverHandlesShareServers: false 
  ManilaCephFSNativeCephFSConfPath: '/etc/ceph/ceph.conf'
  ManilaCephFSNativeCephFSAuthId: 'manila' 
  ManilaCephFSNativeCephFSClusterName: 'ceph'
  ManilaCephFSNativeCephFSEnableSnapshots: true
